// products-data.jsx — shared product catalog for the shop kit.
// Twelve illustrative products spanning Hair, Skin, Body, Home & ritual.
window.HARAV_PRODUCTS = [
  { id: 'p01', cat: 'Hair', name: 'Quietude Hair Oil',
    type: 'Pre-wash · 50ml', price: 64,
    blurb: 'A warm, weightless oil for the lengths. Argan, camellia, a breath of vetiver.',
    ritual: 'Warm two drops between palms. Press through mid-lengths to ends. Leave for an hour — or sleep in it.',
    img: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=900&q=85' },
  { id: 'p02', cat: 'Hair', name: 'Rosemary & Sage Tonic',
    type: 'Scalp · 100ml', price: 52,
    blurb: 'A clarifying tonic for the scalp. Slow-distilled, low-fragrance.',
    ritual: 'Section dry hair. Apply with the pipette directly to scalp. Massage. Leave.',
    img: 'https://images.unsplash.com/photo-1556228852-80b6e5eeff06?w=900&q=85' },
  { id: 'p03', cat: 'Hair', name: 'Linen Hair Salve',
    type: 'Styling · 60g', price: 46,
    blurb: 'A matte finishing salve. Holds a wave without holding it down.',
    ritual: 'Warm a small amount. Work through styled hair from the mid-shaft.',
    img: 'https://images.unsplash.com/photo-1631730486572-226d1f595b68?w=900&q=85' },
  { id: 'p04', cat: 'Hair', name: 'Pressed Cream Conditioner',
    type: 'Wash · 200ml', price: 38,
    blurb: 'Slow-pressed shea, sweet almond, a quiet rose. For coloured and dry hair.',
    ritual: 'After washing. Apply mid-shaft to ends. Wait three minutes. Rinse cool.',
    img: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=900&q=85' },

  { id: 'p05', cat: 'Skin', name: 'Dawn Cleansing Balm',
    type: 'Cleanser · 90g', price: 58,
    blurb: 'A balm that melts at the temperature of your hand. Removes the day in one pass.',
    ritual: 'Scoop a small amount onto dry skin. Massage for one full minute. Emulsify with warm water.',
    img: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=900&q=85' },
  { id: 'p06', cat: 'Skin', name: 'Champagne Masque',
    type: 'Mask · 60ml', price: 78,
    blurb: 'Our signature in-spa masque, miniaturised. Gold leaf, kaolin, peptides.',
    ritual: 'Apply a thin veil to cleansed skin. Leave fifteen minutes. Sweep off with a warm cloth.',
    img: 'https://images.unsplash.com/photo-1583241800698-9c2e0c91d0d1?w=900&q=85' },
  { id: 'p07', cat: 'Skin', name: 'Vellum Face Oil',
    type: 'Treatment · 30ml', price: 92,
    blurb: 'A serum-oil hybrid. Squalane, bakuchiol, a single drop of jasmine.',
    ritual: 'Three drops, evening only. Press into damp skin after your serum.',
    img: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=900&q=85' },
  { id: 'p08', cat: 'Skin', name: 'Hand Pressed Serum',
    type: 'Treatment · 30ml', price: 84,
    blurb: 'A quiet vitamin C, suspended in glycerin. No sting, no rush.',
    ritual: 'Two pumps onto damp skin, morning. Press in with the heels of the hands.',
    img: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=900&q=85' },

  { id: 'p09', cat: 'Body', name: 'Linen & Bergamot Bath Salt',
    type: 'Soak · 400g', price: 36,
    blurb: 'Coarse French salt. A handful softens the water and lifts the room.',
    ritual: 'Run the bath warm, not hot. A small handful, dissolved. Forty minutes.',
    img: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=900&q=85' },
  { id: 'p10', cat: 'Body', name: 'Ritual Body Oil',
    type: 'Treatment · 100ml', price: 72,
    blurb: 'A slow oil for after the bath. Sesame, jojoba, neroli.',
    ritual: 'Apply to damp skin. Begin at the feet, work upward, end at the collarbones.',
    img: 'https://images.unsplash.com/photo-1601612628452-9e99ced43524?w=900&q=85' },

  { id: 'p11', cat: 'Home & ritual', name: 'The Quiet Hour Candle',
    type: 'Candle · 220g', price: 64,
    blurb: 'The scent of the salon. Beeswax, cedar, a thread of tobacco.',
    ritual: 'Burn for thirty minutes the first time. Trim the wick afterward.',
    img: 'https://images.unsplash.com/photo-1599751449128-eb7249c3d6b1?w=900&q=85' },
  { id: 'p12', cat: 'Home & ritual', name: 'Rosemary Tea — Loose',
    type: 'Tea · 75g', price: 28,
    blurb: 'A house blend. Rosemary, fennel, lemon verbena, a quiet thyme.',
    ritual: 'A teaspoon per cup. Steep five minutes. Drink warm, not hot.',
    img: 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=900&q=85' },
];
